os:
  - osx
language: node_js

node_js:
  - "node"
  - "lts/*"

#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3

script:
  - npm test

branches:
  only:
    - master
    - typescript-experiments

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never
